json.Groups @groups
json.Leafs @leafs
json.Sides @sides
json.Notes @terms
json.GroupsOfMatchingLeafs @groupsOfMatchingLeafs
json.LeafsOfMatchingSides @leafsOfMatchingSides
json.GroupsOfMatchingSides @groupsOfMatchingSides
json.GroupsOfMatchingNotes @groupsOfMatchingTerms
json.LeafsOfMatchingNotes @leafsOfMatchingTerms
json.SidesOfMatchingNotes @sidesOfMatchingTerms
json.visibleAttributes @visibleAttributes
