json.Groups @groups
json.Leafs @leafs
json.Sides @sides
json.Terms @terms
json.GroupsOfMatchingLeafs @groupsOfMatchingLeafs
json.LeafsOfMatchingSides @leafsOfMatchingSides
json.GroupsOfMatchingSides @groupsOfMatchingSides
json.groupsOfMatchingTerms @groupsOfMatchingTerms
json.LeafsOfMatchingTerms @leafsOfMatchingTerms
json.SidesOfMatchingTerms @sidesOfMatchingTerms
json.visibleAttributes @visibleAttributes
